build:
  stage: build
  script:
    - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_TAG .

test:
  stage: test
  script:
    - docker run  $CI_PROJECT_NAME:$CI_COMMIT_TAG pytest

publish:
  stage: deploy
  script:
    - echo $HARBOR_REGISTRY $HARBOR_USER $HARBOR_PASSWORD
    - docker login "$HARBOR_REGISTRY" -u "$HARBOR_USER" -p "$HARBOR_PASSWORD"
    - docker tag $CI_PROJECT_NAME:$CI_COMMIT_TAG reg.company.com/$CI_PROJECT_NAME/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker push reg.company.com/$CI_PROJECT_NAME/$CI_PROJECT_NAME:$CI_COMMIT_TAG

cleanup:
  stage: .post
  script:
    - docker rmi --force $CI_PROJECT_NAME:$CI_COMMIT_TAG
    - docker rmi --force reg.company.com/$CI_PROJECT_NAME/$CI_PROJECT_NAME:$CI_COMMIT_TAG
